(async function(){
  const {PDFDocument,StandardFonts,rgb,degrees}=PDFLib;
  const input=document.querySelector('#pdf-input'),zone=document.querySelector('#drop-zone'),list=document.querySelector('#pdf-list'),thumbs=document.querySelector('#thumbs'),status=document.querySelector('#status');
  let files=[],sources=[],pages=[],selectedPage=0;
  const setStatus=(t,c='')=>{status.textContent=t;status.className='status '+c};
  const esc=s=>s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function renderFiles(){list.innerHTML=files.map((f,i)=>`<div class="file-row"><span class="file-name">${i===0?'':' '} ${esc(f.name)}</span><span class="file-meta">${pdfFormatBytes(f.size)} · <button class="btn danger" data-remove-file="${i}" style="padding:5px 8px">Remove</button></span></div>`).join('');list.querySelectorAll('[data-remove-file]').forEach(b=>b.onclick=async()=>{files.splice(+b.dataset.removeFile,1);await buildWorkspace()})}
  pdfBindDrop(zone,input,async fs=>{const added=fs.filter(pdfIsPdf);if(!added.length)return;files=added;await buildWorkspace()});
  async function buildWorkspace(){try{sources=[];pages=[];selectedPage=0;if(!files.length){renderFiles();thumbs.innerHTML='';setStatus('');return}setStatus('Reading PDF pages…');for(let fi=0;fi<files.length;fi++){const doc=await PDFDocument.load(await files[fi].arrayBuffer(),{ignoreEncryption:true});sources.push(doc);doc.getPages().forEach((_,pi)=>pages.push({fi,pi,rotation:0,annotations:[]}))}renderFiles();await renderThumbs();setStatus(pages.length+' page(s) ready. New upload replaces the previous PDF.','ok')}catch(e){console.error(e);files=[];sources=[];pages=[];renderFiles();thumbs.innerHTML='';setStatus('Could not open this PDF. Password protected or unusual PDFs may not work.','error')}}
  async function renderThumbs(){thumbs.innerHTML='';for(let i=0;i<pages.length;i++){const p=pages[i],box=document.createElement('div');box.className='page-thumb'+(i===selectedPage?' selected':'');box.innerHTML=`<canvas></canvas><div class="page-number">Page ${i+1}</div><div class="thumb-actions"><button data-up title="Move up">↑</button><button data-down title="Move down">↓</button><button data-rot title="Rotate">↻</button><button data-text title="Add text">T</button><button data-icon title="Add icon">★</button><button data-del class="delete">Delete</button></div>`;thumbs.appendChild(box);box.onclick=e=>{if(e.target.tagName==='BUTTON')return;selectedPage=i;renderThumbs()};box.querySelector('[data-up]').onclick=()=>move(i,-1);box.querySelector('[data-down]').onclick=()=>move(i,1);box.querySelector('[data-rot]').onclick=()=>{pages[i].rotation=(pages[i].rotation+90)%360;renderThumbs()};box.querySelector('[data-del]').onclick=()=>{pages.splice(i,1);selectedPage=Math.min(selectedPage,pages.length-1);renderThumbs()};box.querySelector('[data-text]').onclick=()=>addAnnotation(i,'text');box.querySelector('[data-icon]').onclick=()=>addAnnotation(i,'icon');await drawPdfThumb(files[p.fi],p.pi,box.querySelector('canvas'),p.rotation)}}
  async function drawPdfThumb(file,pageIndex,canvas,rot){const data=new Uint8Array(await file.arrayBuffer()),doc=await pdfjsLib.getDocument({data}).promise,page=await doc.getPage(pageIndex+1),base=page.getViewport({scale:1}),scale=Math.min(1.4,180/base.width),view=page.getViewport({scale,rotation:rot});canvas.width=view.width;canvas.height=view.height;await page.render({canvasContext:canvas.getContext('2d'),viewport:view,background:'white'}).promise}
  function move(i,d){const j=i+d;if(j<0||j>=pages.length)return;[pages[i],pages[j]]=[pages[j],pages[i]];selectedPage=j;renderThumbs()}
  function addAnnotation(i,type){const val=type==='text'?prompt('Enter the text to add to this page:','PixelLite'):prompt('Enter a simple icon or symbol:','★');if(!val)return;pages[i].annotations.push({type,text:val});selectedPage=i;setStatus('Added '+(type==='text'?'text':'icon')+' to Page '+(i+1)+'. It will appear near the top-left in the exported PDF.','ok')}
  document.querySelector('#clear').onclick=()=>{files=[];sources=[];pages=[];renderFiles();thumbs.innerHTML='';input.value='';setStatus('')};
  document.querySelector('#save').onclick=async()=>{if(!pages.length)return setStatus('Add a PDF first.','error');try{setStatus('Building edited PDF…');const outDoc=await PDFDocument.create(),font=await outDoc.embedFont(StandardFonts.Helvetica),bold=await outDoc.embedFont(StandardFonts.HelveticaBold);for(const item of pages){const src=sources[item.fi],[pg]=await outDoc.copyPages(src,[item.pi]);pg.setRotation(degrees((pg.getRotation().angle+item.rotation)%360));outDoc.addPage(pg);const w=pg.getWidth(),h=pg.getHeight();let y=h-40;for(const a of item.annotations){if(a.type==='text'){pg.drawText(a.text,{x:36,y,size:18,font:bold,color:rgb(.12,.13,.18)})}else{pg.drawText(a.text,{x:36,y,size:24,font,color:rgb(.31,.27,.8)})}y-=34}}
    const footer=(document.querySelector('#footer-text').value||'').trim();if(footer)outDoc.getPages().forEach((pg,i)=>{pg.drawText(footer,{x:28,y:18,size:9,font,color:rgb(.35,.38,.45),opacity:.8});pg.drawText(String(i+1),{x:pg.getWidth()-32,y:18,size:9,font,color:rgb(.35,.38,.45),opacity:.8})});
    const out=await outDoc.save({useObjectStreams:true,addDefaultPage:false});pdfDownload(new Blob([out],{type:'application/pdf'}),'pixellite-edited.pdf');setStatus('Edited PDF downloaded. '+pdfFormatBytes(out.length),'ok')}catch(e){console.error(e);setStatus('Could not save the edited PDF.','error')}};
})();
