(async function(){
  const {PDFDocument,StandardFonts,rgb,degrees}=PDFLib;
  const input=document.querySelector('#pdf-input'),zone=document.querySelector('#drop-zone'),list=document.querySelector('#pdf-list'),thumbs=document.querySelector('#thumbs'),status=document.querySelector('#status');
  let files=[],sources=[],pages=[],selectedFile=0;
  const setStatus=(t,c='')=>{status.textContent=t;status.className='status '+c};
  function renderFiles(){list.innerHTML=files.map((f,i)=>`<div class="file-row"><span class="file-name">${i===selectedFile?'▶ ':''}${f.name}</span><span class="file-meta">${pdfFormatBytes(f.size)} · <button class="btn secondary" data-select="${i}" style="padding:5px 8px">Use</button></span></div>`).join('');list.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>{selectedFile=+b.dataset.select;renderFiles()})}
  pdfBindDrop(zone,input,async fs=>{const added=fs.filter(pdfIsPdf);if(!added.length)return;files.push(...added);renderFiles();await buildWorkspace()});
  async function buildWorkspace(){try{setStatus('Reading PDF pages…');sources=[];pages=[];for(let fi=0;fi<files.length;fi++){const doc=await PDFDocument.load(await files[fi].arrayBuffer(),{ignoreEncryption:true});sources.push(doc);doc.getPages().forEach((_,pi)=>pages.push({fi,pi,rotation:0}))}await renderThumbs();setStatus(pages.length+' page(s) ready to edit.','ok')}catch(e){console.error(e);setStatus('Could not open one of the PDFs. Password protected PDFs may not work.','error')}}
  async function renderThumbs(){thumbs.innerHTML='';for(let i=0;i<pages.length;i++){const p=pages[i];const box=document.createElement('div');box.className='page-thumb';box.innerHTML=`<canvas></canvas><div class="page-number">Page ${i+1}</div><div class="thumb-actions"><button data-up>↑</button><button data-down>↓</button><button data-rot>↻</button><button data-del>Delete</button></div>`;thumbs.appendChild(box);box.querySelector('[data-up]').onclick=()=>move(i,-1);box.querySelector('[data-down]').onclick=()=>move(i,1);box.querySelector('[data-rot]').onclick=()=>{pages[i].rotation=(pages[i].rotation+90)%360;renderThumbs()};box.querySelector('[data-del]').onclick=()=>{pages.splice(i,1);renderThumbs()};await drawPdfThumb(files[p.fi],p.pi,box.querySelector('canvas'),p.rotation)} }
  async function drawPdfThumb(file,pageIndex,canvas,rot){if(!window.pdfjsLib)return;const data=new Uint8Array(await file.arrayBuffer());const doc=await pdfjsLib.getDocument({data}).promise;const page=await doc.getPage(pageIndex+1);const base=page.getViewport({scale:1});const scale=Math.min(1.5,180/base.width);const view=page.getViewport({scale,rotation:rot});canvas.width=view.width;canvas.height=view.height;await page.render({canvasContext:canvas.getContext('2d'),viewport:view}).promise}
  function move(i,d){const j=i+d;if(j<0||j>=pages.length)return;[pages[i],pages[j]]=[pages[j],pages[i]];renderThumbs()}
  document.querySelector('#clear').onclick=()=>{files=[];sources=[];pages=[];renderFiles();thumbs.innerHTML='';setStatus('')};
  document.querySelector('#save').onclick=async()=>{if(!pages.length)return setStatus('Add a PDF first.','error');try{setStatus('Building edited PDF…');const outDoc=await PDFDocument.create();for(const item of pages){const src=sources[item.fi];const [pg]=await outDoc.copyPages(src,[item.pi]);pg.setRotation(degrees((pg.getRotation().angle+item.rotation)%360));outDoc.addPage(pg)}const text=(document.querySelector('#watermark').value||'').trim();if(text){const font=await outDoc.embedFont(StandardFonts.Helvetica);outDoc.getPages().forEach((pg,i)=>{pg.drawText(text,{x:28,y:18,size:9,font,color:rgb(.35,.38,.45),opacity:.8});pg.drawText(String(i+1),{x:pg.getWidth()-32,y:18,size:9,font,color:rgb(.35,.38,.45),opacity:.8})})}const out=await outDoc.save({useObjectStreams:true});pdfDownload(new Blob([out],{type:'application/pdf'}),'pixellite-edited.pdf');setStatus('Edited PDF downloaded. '+pdfFormatBytes(out.length),'ok')}catch(e){console.error(e);setStatus('Could not save the edited PDF.','error')}};
})();
